### PR TITLE
Update link to most recent docs.

### PR DESCRIPTION
**Pull request by apalmblad**

### CODE REVIEW

**Review by vincent-truong — APPROVED** [review]

**Comment by elquimista** [comment]
Only update link without actual v4 API support?

**Comment by elquimista** [comment]
Is any of you already (secretly) working on supporting v4 API? Otherwise I'm going to fork and issue a PR sooner or later.

**Comment by vtruong74** [comment]
Hi @elquimista, we're not actively working on a `clio_connect` for v4, but would be happy to review any pr's you have.

**Comment by nicholasshirley** [comment]
@vtruong74 Is Clio officially adopting/maintaining this gem or should PR go to the original repo?

**Pull request merged**
